In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
nba = pd.read_csv("final_table.csv", index_col=0)
nba.fillna(0, inplace=True)
nba.sample(10)

,Player,tm,pos,yr2019_20,avg_cost_per_pt,Age,PER,pts,g,mp,ast,stl,blk
387,Monta Ellis,0,0,2245400.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,Mike Conley,UTA,PG,32511623.0,48165.37,32.0,14.1,675.0,47.0,1363.0,208.0,36.0,5.0
596,Stanton Kidd,UTA,SF,250000.0,inf,27.0,-13.7,0.0,4.0,15.0,1.0,0.0,0.0
567,Marquese Chriss,GSW,PF,758804.0,1384.68,22.0,19.5,548.0,59.0,1196.0,114.0,39.0,62.0
188,Marvin Bagley,0,0,8556120.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
495,Vlatko Čančar,DEN,SF,1517981.0,89293.00,22.0,11.4,17.0,14.0,45.0,3.0,1.0,1.0
114,Mason Plumlee,DEN,C,14041096.0,32130.65,29.0,18.8,437.0,61.0,1057.0,154.0,33.0,38.0
194,Kentavious Caldwell-Pope,LAL,SG,8089282.0,12541.52,26.0,11.0,645.0,69.0,1762.0,111.0,57.0,14.0
541,Justin Hamilton,0,0,1000000.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
205,Luka Dončić,DAL,PG,7683360.0,4368.03,20.0,27.6,1759.0,61.0,2047.0,538.0,62.0,14.0

In [3]:
nba.shape

(526, 13)

In [21]:
print(nba[nba['g']==0.0])

                  Player tm pos   yr2019_20  avg_cost_per_pt  Age  PER  pts  \
3              John Wall  0   0  37800000.0              0.0  0.0  0.0  0.0
6           Kevin Durant  0   0  37199000.0              0.0  0.0  0.0  0.0
10         Klay Thompson  0   0  32742000.0              0.0  0.0  0.0  0.0
73          Tim Hardaway  0   0  18150000.0              0.0  0.0  0.0  0.0
98           Kelly Oubre  0   0  15625000.0              0.0  0.0  0.0  0.0
..                   ... ..  ..         ...              ...  ...  ...  ...
635  Sir'Dominic Pointer  0   0     50752.0              0.0  0.0  0.0  0.0
640        Isaiah Taylor  0   0     50000.0              0.0  0.0  0.0  0.0
641          Tyler Lydon  0   0     50000.0              0.0  0.0  0.0  0.0
642      Hollis Thompson  0   0     50000.0              0.0  0.0  0.0  0.0
643           Tyler Ulis  0   0     50000.0              0.0  0.0  0.0  0.0

       g   mp  ast  stl  blk
3    0.0  0.0  0.0  0.0  0.0
6    0.0  0.0  0.0  0.0  0.0
10   0.0  0.0  0.0  0.0  0.0
73   0.0  0.0  0.0  0.0  0.0
98   0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...
635  0.0  0.0  0.0  0.0  0.0
640  0.0  0.0  0.0  0.0  0.0
641  0.0  0.0  0.0  0.0  0.0
642  0.0  0.0  0.0  0.0  0.0
643  0.0  0.0  0.0  0.0  0.0

[63 rows x 13 columns]

In [5]:
# Assign the data to X and y
X = nba[["pts","g","mp","stl","ast", "blk", "PER"]]
# X=nba['PER']
y = nba["yr2019_20"].values.reshape(-1, 1)
print(X.shape, y.shape)

(526, 7) (526, 1)

In [6]:
y.shape
# print(X[X['pts']==0])

(526, 1)

In [7]:
# Use train_test_split to create training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

In [8]:
# Create the model using LinearRegression
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [9]:
# Fit the model to the training data and calculate the scores for the training and testing data

model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)

print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Training Score: 0.41340242415636286
Testing Score: 0.1856603210989889

In [15]:
coeff_df =pd.DataFrame(model.coef_[0], X.columns, columns=['Coefficient'])
coeff_df

##This means that for a unit increase in "pts", there is a increase of $8498.86 in salary

       Coefficient
pts    7536.095090
g   -228905.432933
mp     5581.621265
stl  -58577.173467
ast   19988.879399
blk   28560.155265
PER  295188.023557

In [16]:
y_pred = model.predict(X_test)
# salary_pred= "${:.2f}".format(salary_pred)
#print(y_pred)
pred_df = pd.DataFrame(y_pred, columns=['Predicted_Salary'])
#pred_df=pred_df.style.format("${:,.2f}")
pred_df

     Predicted_Salary
0        1.174489e+07
1        9.921305e+06
2        3.150587e+07
3        4.163024e+06
4        3.460380e+06
..                ...
153      7.338696e+06
154      1.800720e+06
155      3.460380e+06
156      1.442982e+07
157      6.106624e+06

[158 rows x 1 columns]

In [17]:
salary_pred = pd.DataFrame({"Actual Salary": y_test[0], "Predicted": y_pred[0]})
#salary_pred=salary_pred.style.format("${:,.2f}")
salary_pred

   Actual Salary     Predicted
0      7936508.0  1.174489e+07

In [18]:
y_test=(y_test)
y_test = pd.DataFrame(y_test, columns=['actual_salary'])
#y_test=y_test.style.format("${:,.2f}")
y_test

     actual_salary
0        7936508.0
1       13437500.0
2       37436858.0
3        1620564.0
4        1290960.0
..             ...
153      1620564.0
154     13000000.0
155        50752.0
156     17000000.0
157      7333333.0

[158 rows x 1 columns]

In [19]:
comparisons = pd.concat([y_test, pred_df], axis=1, sort=False)
#comparisons=comparisons.style.format("${:,.2f}")
# comparison = comparisons.sample(10)
#comparison=comparison.style.format("${:,.2f}")
#print(comparisons)
#print(comparisons.sample(10))

In [20]:
comparisons.style.format("${:,.2f}")

In [ ]:
# comparisons = pd.DataFrame({"Actual Salary": y_test,
#                            "Predicted Salary": pred_df})
# comparisons

In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))